// GET Todos section

export const GET_TODOS_REQUEST = "GET_TODOS_REQUEST";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const GET_TODOS_ERROR = "GET_TODOS_ERROR";

// POST Todos section
export const POST_TODOS_REQUEST = "POST_TODOS_REQUEST";
export const POST_TODOS_SUCCESS = "POST_TODOS_SUCCESS";
export const POST_TODOS_ERROR = "POST_TODOS_ERROR";
